### ISSUE TITLE
BlazorsvgHelper not found

### ISSUE THREAD

**Issue by Draethorian** [Lupusa87/BlazorPaint#1]
BlazorSVGHelper not found, had to get it as a nugetpackage for PaintComponent. Then it couldn't resolve   
p.transform
              p.transform = "scale(" + Par_Object.Scale.x + "," + Par_Object.Scale.y + ")";
at CompMySVG line 220
Error	CS1061	'path' does not contain a definition for 'transform' and no accessible extension method 'transform' accepting a first argument of type 'path' could be found (are you missing a using directive or an assembly reference?)

**Comment by Lupusa87** [comment]
It is another repo, you could download it and reference.
Sorry I was not watching this repo and missed this issue.
